@taurus_HostAddress = http://localhost:8000

GET {{taurus_HostAddress}}
###

GET {{taurus_HostAddress}}/tasks
###

GET {{taurus_HostAddress}}/tasks/1

###
POST {{taurus_HostAddress}}/tasks
Content-Type: application/json

{
  "title": "pegar elden ring no hydra launcher"
}

###
PATCH  {{taurus_HostAddress}}/tasks/1/complete