@taurus_HostAddress = http://localhost:8765
GET {{taurus_HostAddress}}
###

GET {{taurus_HostAddress}}/tasks
###

GET {{taurus_HostAddress}}/tasks/1

###
POST {{taurus_HostAddress}}/tasks
Content-Type: application/json

{
  "title": "tarefa teste a ser deletada."
}

###
PATCH  {{taurus_HostAddress}}/tasks/8/complete

###
DELETE {{taurus_HostAddress}}/tasks/8